on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
      - master
  workflow_dispatch:  # 手动触发
jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: |
          npm install
      - name: Publish to Cloudflare Workers
        env:
          CLOUDFLARE_ACCOUNT_ID:  ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "MY_SECRET is set to: ${{ secrets.CF_API_TOKEN }}" && npm run deploy

